version: '3'
services:
  api:
    image: rails
    container_name: api
    command:
      "bash -c -l 'bundle install && bundle exec puma'"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
